name: Build Pico

on:
  push:
    paths:
      - 'pico/**'
  pull_request:
    paths:
      - 'pico/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: pico

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install cmake python3 build-essential gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib -y

      - name: Build project
        run: mkdir build && cd build && cmake .. && make
